import { ChatGoogleGenerativeAI } from "@langchain/google-genai";
import { createAgent, HumanMessage } from "langchain";
import { Command } from "@langchain/langgraph";
import *  as z from "zod";
import { AgentState } from "./state";
// Initialize Gemini LLM
const geminiLLM = new ChatGoogleGenerativeAI({
  model: "gemini-2.5-flash",
  apiKey: process.env.GOOGLE_API_KEY,
  temperature: 0.1,
});

const outputSchema=z.object({
    explanation: z.string().describe("Detailed explanation of the code or programming concept requested by the user"),
    msg2Agent: z.string().describe("Message to be sent to the supervisor agent after explanation"),
})

const agent=createAgent({
    model: geminiLLM,
    systemPrompt: `You are the Explainer agent in a multi-agent coding assistant system.
    Your role is to provide clear and concise explanations of code snippets and programming concepts to users.
    Analyze the user's questions and the provided code to deliver informative explanations that enhance the user's understanding.
    If the user question is unrelated to code explanation, inform the user that you can only help with code explanations.
    The user can ask questions from both his own code and the code generated by AI.
    And the user can ask question about the problem description as well.`,
    
    responseFormat: outputSchema,

})

const runExplainerAgent=async(state:AgentState)=>{
    const response=await agent.invoke({
        messages:[ new HumanMessage(`User Code: ${state.userCode} AICode: ${state.AICode}
        Problem Description: ${state.problem}
        User Question: ${state.userQuestion[state.userQuestion.length - 1]}`)],
    });
    state.flow.push("explainer");
    state.messages.push(response.structuredResponse.msg2Agent);

    return new Command({     
        goto: "supervisor",
        update: {
          flow: state.flow,
          messages: state.messages,
          userQuestion: [
            ...state.userQuestion,
          ],
        },
      });

}

export default runExplainerAgent;